# fly.toml app configuration file generated for amol-nama on 2026-08-28T18:33:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'amol-nama'
primary_region = 'sin'

[build]

[deploy]
  strategy = 'immediate'

[env]
  PYTHONUNBUFFERED = '1'

[processes]
  app = 'python bot.py'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
